---
# Configure kdump

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ kdump_services_enable }}"
  when: kdump_enable_service
